sudo: required
services:
  - docker

before_install:
  - docker build -t shaharl/sami1ogic -f Dockerfile.dev .

script:
  - docker run shaharl/sami1ogic npm run test -- --coverage

deploy:
  provider: heroku
  api_key: 
    secure: "31062e86-8c59-40dd-9162-bd040f865680"